---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: nginx
        state: latest
    - name: Start nginx server
      service:
        name: nginx
        state: started
        enabled: True


